CREATE SYNONYM STUDENT FOR STUDENT_MASTER@TRAXLINK.WORLD;

CREATE SYNONYM STUD_XCRSE FOR STUD_XCRSE@TRAXLINK.WORLD;

CREATE SYNONYM PROV_EXAM FOR PROV_EXAM@TRAXLINK.WORLD;

CREATE SYNONYM STUD_GRAD_ASSMT FOR STUD_GRAD_ASSMT@TRAXLINK.WORLD;

CREATE SYNONYM TAB_SCHOOL FOR TAB_SCHOOL@TRAXLINK.WORLD;
